"""add document_no to insights_data

Revision ID: [auto_generated_id]
Revises: d34b33073e50
Create Date: 2025-01-08 [auto_generated_timestamp]

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '[auto_generated_id]'
down_revision: Union[str, None] = 'd34b33073e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights_data', sa.Column('document_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights_data', 'document_no')
    # ### end Alembic commands ###