"""Initial clean migration

Revision ID: 7b7a4de2cbc7
Revises: 
Create Date: 2025-07-03 16:42:36.562151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b7a4de2cbc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliverychallan_data')
    op.drop_table('invoice_data')
    op.drop_table('transferorder_rgp_data')
    op.add_column('document_data', sa.Column('warehouse_code', sa.String(length=100), nullable=True))
    op.alter_column('document_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('document_data', 'site',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'document_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('document_data', 'e_way_bill_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'transporter_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'vehicle_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'irn_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'route_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'route_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'direct_dispatch',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'total_quantity',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('document_data', 'from_warehouse_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'to_warehouse_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'sub_document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'salesman',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('insights_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('insights_data', 'document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('insights_data', 'sub_document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('insights_data', 'vehicle_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('insights_data', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('insights_data', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('insights_data', 'movement_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('insights_data', 'warehouse_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('insights_data', 'site_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insights_data', 'site_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'warehouse_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'movement_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('insights_data', 'warehouse_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'vehicle_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'sub_document_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'document_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('insights_data', 'gate_entry_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'salesman',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'sub_document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'to_warehouse_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'from_warehouse_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'total_quantity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'direct_dispatch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'route_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'route_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'warehouse_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'irn_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'vehicle_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'transporter_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'e_way_bill_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'document_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_data', 'document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'site',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'document_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('document_data', 'warehouse_code')
    op.create_table('transferorder_rgp_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('direct_dispatch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('salesman', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='transferorder_rgp_data_pkey')
    )
    op.create_table('invoice_data',
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='invoice_data_pkey')
    )
    op.create_table('deliverychallan_data',
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('route_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='deliverychallan_data_pkey')
    )
    # ### end Alembic commands ###
