"""Edit Function

Revision ID: d34b33073e50
Revises: 7b7a4de2cbc7
Create Date: 2025-07-31 18:08:09.828645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34b33073e50'
down_revision: Union[str, None] = '7b7a4de2cbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_data')
    op.drop_table('transferorder_rgp_data')
    op.drop_table('deliverychallan_data')
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('idx_insights_data_driver_name', table_name='insights_data')
    op.drop_index('idx_insights_data_edit_count', table_name='insights_data')
    op.drop_index('idx_insights_data_last_edited_at', table_name='insights_data')
    op.drop_column('insights_data', 'total_quantity')
    op.drop_column('mfabric_deliverychallan_data', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfabric_deliverychallan_data', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('insights_data', sa.Column('total_quantity', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_insights_data_last_edited_at', 'insights_data', ['last_edited_at'], unique=False)
    op.create_index('idx_insights_data_edit_count', 'insights_data', ['edit_count'], unique=False)
    op.create_index('idx_insights_data_driver_name', 'insights_data', ['driver_name'], unique=False)
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('deliverychallan_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='deliverychallan_data_pkey1')
    )
    op.create_table('transferorder_rgp_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('direct_dispatch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('salesman', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='transferorder_rgp_data_pkey1')
    )
    op.create_table('invoice_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name='invoice_data_pkey1')
    )
    # ### end Alembic commands ###
