"""make document_no nullable in mfabric tables

Revision ID: 03c919435c77
Revises: 87f5a97ce9bd
Create Date: 2025-08-01 13:04:38.537822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c919435c77'
down_revision: Union[str, None] = '87f5a97ce9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
