"""initial migration

Revision ID: 6e5b54898a6b
Revises: 
Create Date: 2025-07-31 17:59:05.156422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5b54898a6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_data',
    sa.Column('document_no', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=100), nullable=True),
    sa.Column('transporter_name', sa.String(length=100), nullable=True),
    sa.Column('vehicle_no', sa.String(length=100), nullable=True),
    sa.Column('irn_no', sa.String(length=100), nullable=True),
    sa.Column('warehouse_code', sa.String(length=100), nullable=True),
    sa.Column('warehouse_name', sa.String(length=100), nullable=True),
    sa.Column('route_code', sa.String(length=100), nullable=True),
    sa.Column('route_no', sa.String(length=100), nullable=True),
    sa.Column('customer_code', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('direct_dispatch', sa.String(length=100), nullable=True),
    sa.Column('total_quantity', sa.String(length=100), nullable=True),
    sa.Column('gate_entry_no', sa.String(length=20), nullable=True),
    sa.Column('from_warehouse_code', sa.String(length=100), nullable=True),
    sa.Column('to_warehouse_code', sa.String(length=100), nullable=True),
    sa.Column('sub_document_type', sa.String(length=100), nullable=True),
    sa.Column('salesman', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('insights_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_entry_no', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('sub_document_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('warehouse_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('warehouse_code', sa.String(length=50), nullable=True),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('security_username', sa.String(length=255), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('km_reading', sa.String(length=10), nullable=True),
    sa.Column('loader_names', sa.String(length=200), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_master',
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_code')
    )
    op.create_table('mfabric_deliverychallan_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('route_no', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('mfabric_invoice_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('mfabric_transferorder_rgp_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('sub_document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('from_warehouse_code', sa.String(length=255), nullable=True),
    sa.Column('to_warehouse_code', sa.String(length=255), nullable=True),
    sa.Column('route_code', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('direct_dispatch', sa.String(length=255), nullable=True),
    sa.Column('salesman', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('users_master',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('warehouse_code', sa.String(length=50), nullable=True),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_code'], ['location_master.warehouse_code'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_master')
    op.drop_table('mfabric_transferorder_rgp_data')
    op.drop_table('mfabric_invoice_data')
    op.drop_table('mfabric_deliverychallan_data')
    op.drop_table('location_master')
    op.drop_table('insights_data')
    op.drop_table('document_data')
    # ### end Alembic commands ###
